name: ci
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        ports: 
        - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U postgres -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
        run: |
          docker-compose exec flask_app pytest
